Project_09/Areas/Angular/Controllers/SPAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Project_09.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace Ex_09_Project.Areas.Angular.Controllers
{
    [Area("Angular")]
    public class SPAController : Controller
    {
        IBatchRepository repo;
        public SPAController (IBatchRepository repo) { this.repo = repo; }
        public IActionResult Index()
        {
            return View();
        }
        public JsonResult TraineeList()
        {
            var data = repo.GetTrainees().Select(x => new {
                x.TraineeId, x.TraineeName, TSP=x.TSP.ToString(), x.BatchId, BatchName=x.Batch.BatchName,Contact=x.Contact,TID=x.TID
            }).ToList();
            return Json(data);
        }
    }
}

Project_09/Controllers/BatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Project_09.Models;
using Project_09.Repositories;
using Project_09.ViewModels;

namespace Project_09.Controllers
{
    [Authorize]
    public class BatchesController : Controller
    {
        IBatchRepository repo;
        public BatchesController(IBatchRepository repo) { this.repo = repo; }
        [AllowAnonymous]
        public IActionResult Index(int pg = 1)
        {
            var data = repo.GetBatches().OrderBy(x => x.BatchId);
            ViewBag.Pager = new PagerModel
            {
                TotalPages = (int)Math.Ceiling((double)data.Count() / 5),
                CurrentPage = pg
            };
            return View(data.Skip((pg - 1) * 5).Take(5).ToList());
        }
        [AllowAnonymous]
        public IActionResult Summary(int pg = 1, string sort = "", string search = "")
        {
            //Thread.Sleep(2000);
            var data = repo.GetSummary();
            ViewBag.Pager = new PagerModel
            {
                TotalPages = (int)Math.Ceiling((double)data.Count() / 5),
                CurrentPage = pg
            };
            if (sort == "") { ViewBag.NameSort = "name"; }
            ViewBag.NameSort = sort == "name" ? "name_desc" : "name";
            ViewBag.CountSort = sort == "count" ? "count_desc" : "count";

            ViewBag.CurrentSort = sort == "" ? "name" : sort;
            ViewBag.Search = search;
            switch (sort)
            {
                case "name":
                    data = data.OrderBy(x => x.BatchName);
                    break;
                case "name_desc":
                    data = data.OrderByDescending(x => x.BatchName);
                    break;
                case "count":
                    data = data.OrderBy(x => x.TraineeCount);
                    break;
                case "count_desc":
                    data = data.OrderByDescending(x => x.TraineeCount);
                    break;
                default:
                    data = data.OrderBy(x => x.BatchId);
                    break;
            }
            if (!string.IsNullOrEmpty(search))
            {
                data = data.Where(x => x.BatchName.ToLower().StartsWith(search.ToLower()));
            }
            var modelData = data.Skip((pg - 1) * 5).Take(5).ToList();
            ///////////////////////////////////////////////////////////////////////
            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("_BatchSummary", modelData);
            }
            ///////////////////////////////////////////////////////////////////////
            return View(modelData);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Batch dept)
        {
            if (ModelState.IsValid)
            {
                repo.InsertBatch(dept);
                return RedirectToAction("Index");
            }
            return View(dept);
        }
        public IActionResult Edit(int id)
        {
            var batch = repo.GetBatchById(id);
            if (batch == null)
            {
                return NotFound();
            }
            return View(batch);
        }
        [HttpPost]
        public IActionResult Edit(Batch batch)
        {
            if (ModelState.IsValid)
            {
                repo.EditBatch(batch);
                return RedirectToAction("Index");
            }
            return View(batch);
        }
        public IActionResult Delete(int id)
        {
            var batch = repo.GetBatchById(id);
            if (batch == null)
            {
                return NotFound();
            }
            return View(batch);
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult ApplyDelete(int id)
        {

            repo.DeleteBatch(id);
            return RedirectToAction("Index");


        }


    }
}

Project_09/Controllers/TraineesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project_09.Models;

namespace Project_09.Controllers
{
    [Authorize]
    public class TraineesController : Controller
    {
        private readonly BatchDbContext _context;

        public TraineesController(BatchDbContext context)
        {
            _context = context;
        }

 [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var batchDbContext = _context.Trainees.Include(t => t.Batch);
            return View(await batchDbContext.ToListAsync());
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainee = await _context.Trainees
                .Include(t => t.Batch)
                .FirstOrDefaultAsync(m => m.TraineeId == id);
            if (trainee == null)
            {
                return NotFound();
            }

            return View(trainee);
        }


        public IActionResult Create()
        {
            ViewData["BatchId"] = new SelectList(_context.Batches, "BatchId", "BatchName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TraineeId,TraineeName,Contact,TID,TSP,BatchId")] Trainee trainee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trainee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BatchId"] = new SelectList(_context.Batches, "BatchId", "BatchName", trainee.BatchId);
            return View(trainee);
        }

        // GET: Trainees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainee = await _context.Trainees.FindAsync(id);
            if (trainee == null)
            {
                return NotFound();
            }
            ViewData["BatchId"] = new SelectList(_context.Batches, "BatchId", "BatchName", trainee.BatchId);
            return View(trainee);
        }

    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TraineeId,TraineeName,Contact,TID,TSP,BatchId")] Trainee trainee)
        {
            if (id != trainee.TraineeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trainee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TraineeExists(trainee.TraineeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BatchId"] = new SelectList(_context.Batches, "BatchId", "BatchName", trainee.BatchId);
            return View(trainee);
        }

  
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainee = await _context.Trainees
                .Include(t => t.Batch)
                .FirstOrDefaultAsync(m => m.TraineeId == id);
            if (trainee == null)
            {
                return NotFound();
            }

            return View(trainee);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var trainee = await _context.Trainees.FindAsync(id);
            _context.Trainees.Remove(trainee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TraineeExists(int id)
        {
            return _context.Trainees.Any(e => e.TraineeId == id);
        }
    }
}

Project_09/Views/Shared/_BatchSummary.cshtml
@model IEnumerable<Project_09.ViewModels.BatchVM>




<table class="table table-bordered">
    <thead class="thead-light">
        <tr>

            <th>


                <a data-ajax="true"
                   data-ajax-loading="#loading"
                   data-ajax-mode="replace"
                   data-ajax-update="#holder"
                   href='@Url.Action("Summary", "Batches", new { sort=ViewBag.NameSort, search=ViewBag.Search})'>
                    @Html.DisplayNameFor(model => model.BatchName)
                    <i class="fa @(ViewBag.NameSort == "name"? "fa-chevron-down": "fa-chevron-up")"></i>
                </a>






            </th>
            <th>
                <a data-ajax="true"
                   data-ajax-loading="#loading"
                   data-ajax-mode="replace"
                   data-ajax-update="#holder"
                   href='@Url.Action("Summary", "Batches", new { sort=ViewBag.CountSort, search=ViewBag.Search})'>
                    @Html.DisplayNameFor(model => model.TraineeCount)
                    <i class="fa @(ViewBag.CountSort == "count"? "fa-chevron-down": "fa-chevron-up")"></i>
                </a>
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.BatchName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TraineeCount)
                </td>

            </tr>
        }
    </tbody>
</table>
<div class="d-flex flex-row-reverse">
    <ul class="pagination pagination-sm">
        @if (ViewBag.Pager.CurrentPage > 1)
        {
            <li class="page-item">
                <a class="page-link" data-ajax="true"
                   data-ajax-loading="#loading"
                   data-ajax-mode="replace"
                   data-ajax-update="#holder"
                   href='@Url.Action("Summary", "Batches", new { pg = ViewBag.Pager.CurrentPage-1, sort=ViewBag.CurrentSort, search=ViewBag.Search})'>
                    <i class="fa fa-long-arrow-left"></i>
                </a>
            </li>
        }
        @for (int i = 1; i <= ViewBag.Pager.TotalPages; i++)
        {
            if (i == ViewBag.Pager.CurrentPage)
            {
                <li class="page-item active"><span class="page-link">@i</span></li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" data-ajax="true"
                       data-ajax-loading="#loading"
                       data-ajax-mode="replace"
                       data-ajax-update="#holder"
                       href='@Url.Action("Summary", "Batches", new { pg = i, sort=ViewBag.CurrentSort, search=ViewBag.Search})'>@i</a>

                </li>
            }

        }
        @if (ViewBag.Pager.CurrentPage < ViewBag.Pager.TotalPages)
        {
            <li class="page-item">
                <a class="page-link" data-ajax="true"
                   data-ajax-loading="#loading"
                   data-ajax-mode="replace"
                   data-ajax-update="#holder"
                   href='@Url.Action("Summary", "Batches", new { pg = ViewBag.Pager.CurrentPage+1, sort=ViewBag.CurrentSort, search=ViewBag.Search})'>
                    <i class="fa fa-long-arrow-right"></i>
                </a>
            </li>
        }
    </ul>
</div>

Project_09/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ex_09_Project</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav style="background-color:#0094ff; color:#fff;min-height:70px" class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Project 09</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Batches" asp-action="Summary">Batch View</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Manage
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Batches" asp-action="Index">Batches</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Trainees" asp-action="Index">Trainees</a>

                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Angular" asp-controller="SPA" asp-action="Index">Angular SPA</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Ex_09_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Project_09/Views/Shared/_success.cshtml
<h2 ><p class=" text-success bg-light">Operation done</p></h2>